language: java
jdk:
  - oraclejdk8
script:
  - mvn clean package
notifications:
  email:
    recipients:
      - 651426288@qq.com
      - zl1030@163.com
    on_success: always # [always|never|change]  default: change
    on_failure: always # [always|never|change]  default: always